image:
  file: gitpod.dockerfile

tasks:
  - command: service mongodb stop ; mongod --journal --bind_ip 0.0.0.0 --port 27017;
  - command: service ssh start ;
ports:
  - port: 22
  - port: 27017
  - port: 3000